### PR TITLE
Update the hello world example.

### PR DESCRIPTION
**Pull request by Mervill**
This is a quick and dirty (and slightly opinionated) rewrite of the `Profiler` class in the example project based on my investigations into integrating this package into [another open source project](https://github.com/space-wizards/space-station-14).

- Change `BeginEvent` to `BeginZone` to be consistent with Tracy terminology. 
  - Exposes more Tracy functionality to show off / demonstrate usage.
  - Don't restrict `color` to just `ColorType` since that enum isn't actually exhaustive.
- Don't worry about caching CStrings in `BeginZone`
  - After `TracyAllocSrclocName` is called the Tracy docs say we don't need to keep these strings around anymore.
  - Is caching the CStrings for performance or memory reasons borne out by data?
- Expose a wrapper to the Tracy `Plot*` functions.
- Pass `null` into `TracyEmitFrameMark` to emit the 'top-level' frame marker so that framing works correctly
  - In the previous version of the example the frame counter did not advance.
- Rename `ProfilerScope` to `ProfilerZone` and move it to its own file.
  - It's a bit bigger now and it could have comments added so it belongs in its own file.
  - 'Zone' to be consistent with Tracy terminology 
- Move `ColorType` to its own folder.
- Disable unsafe blocks
  - I guess it's not terribly impactful either way but it's good to know that the bare-bones example dosen't require it.

### CODE REVIEW

**Comment by clibequilibrium** [comment]
> This is a quick and dirty (and slightly opinionated) rewrite of the `Profiler` class in the example project based on my investigations into integrating this package into [another open source project](https://github.com/space-wizards/space-station-14).
> 
> * Change `BeginEvent` to `BeginZone` to be consistent with Tracy terminology.
>   
>   * Exposes more Tracy functionality to show off / demonstrate usage.
>   * Don't restrict `color` to just `ColorType` since that enum isn't actually exhaustive.
> * Don't worry about caching CStrings in `BeginZone`
>   
>   * After `TracyAllocSrclocName` is called the Tracy docs say we don't need to keep these strings around anymore.
>   * Is caching the CStrings for performance or memory reasons borne out by data?
> * Expose a wrapper to the Tracy `Plot*` functions.
> * Pass `null` into `TracyEmitFrameMark` to emit the 'top-level' frame marker so that framing works correctly
>   
>   * In the previous version of the example the frame counter did not advance.
> * Rename `ProfilerScope` to `ProfilerZone` and move it to its own file.
>   
>   * It's a bit bigger now and it could have comments added so it belongs in its own file.
>   * 'Zone' to be consistent with Tracy terminology
> * Move `ColorType` to its own folder.
> * Disable unsafe blocks
>   
>   * I guess it's not terribly impactful either way but it's good to know that the bare-bones example dosen't require it.

Thank you for the PR, let me test it out and merge it asap.

**Comment by clibequilibrium** [comment]
> Don't worry about caching CStrings in BeginZone
> After TracyAllocSrclocName is called the Tracy docs say we don't need to keep these strings around anymore.
> Is caching the CStrings for performance or memory reasons borne out by data?

I initially cached CStrings because they are allocated under the hood on managed side and are not deallocated automatically. 
https://github.com/bottlenoselabs/c2cs/blob/b0441c1417963191a0178ebad82a9bbb9cc991fe/src/cs/production/Bindgen.Runtime/CString.cs#L184

So the proper thing would be to deallocate them once the Profiler is not needed any longer. I did some profiling though it does seam like memory was not leaking without deallocation at the end. Could you please confirm and I will merge?

**Comment by Mervill** [comment]
~~They should be deallocated automatically since `CString` [implements IDisposable](https://github.com/bottlenoselabs/c2cs/blob/b0441c1417963191a0178ebad82a9bbb9cc991fe/src/cs/production/Bindgen.Runtime/CString.cs#L52-L55)? When the runtime decides to collect a `CString` it should call `Dispose` and free the underlying pointer. It's the same mechanism that drives the call to `TracyEmitZoneEnd` in `ProfilerZone`. This is why you're not seeing memory leaks. Actually, providing C# lifetime to unmanaged objects is the canonical use of `IDisposable`, the fact that people use it to create scope entry/exit semantics is a side effect.~~

Wait I'm reading now that I'm incorrect about this, IDisposable isn't called automatically. The memory should in fact be leaking. I'll uh ... go back to my notes. The part of this post about selecting an appropriate key for the CString cache is still relevant. 

We don't have access to the Tracy [manual lifetime functions](https://github.com/wolfpld/tracy/blob/8b9da2efba6937b66085a52f7281c59293ffe985/public/client/TracyProfiler.hpp#L52-L59) so Tracy expects that the lifetime of the profiling session is equal to the lifetime of the program. Since the `Profiler` class is static it also has the same lifetime expectation. With this in mind it's not ideal to let some external class clear the `CString` cache. You'd likely want to use a (static) finalizer method instead ~~though if you read enough of the docs on finalizers you'll see C# really wants you to use `IDisposable` instead, which is what CString does~~.

There _is_ a nontrivial cost to calling `Marshal.StringToHGlobalAnsi`, especially(?) on the file path passed to zones since paths are more likely to be long strings. I wouldn't oppose caching the `CStrings` to avoid this marshaling cost. What cooked my brain when considering this is: **it's not entirely clear to me how Tracy compares zones for equality** and I wouldn't want to simply key the `CString` cache on the zone name (which can be null!) unless it was clear to me that that's how the Profiler app detects equivalent zones. Otherwise we could end up in a situation where we're reusing cached data on zones that Tracy would otherwise consider separate. The Tracy docs aren't clear enough to me to be confident in selecting the proper key for the cache.

There's also the `TracySourceLocationData` struct that gets generated into the PInvoke class. My brief attempt to use this failed, I'm not actually that experienced with C# interop. If we got this struct working along with `TracyEmitZoneBegin(TracySourceLocationData* srcloc, int active);` then that struct would be ideal for use in the cache instead of having our own struct to hold the data. But again, what's the appropriate key for this?

~~The sum of all of this is that I don't think we should worry about caching CStrings for now. Sorry for the wall of text I actually did agonize over this for a while before deciding that the given implementation is likely good enough~~ my memory about IDisposable functionally was inaccurate.

**Comment by Mervill** [comment]
Updated my reply since I was wrong about `IDisposable`.

**Comment by clibequilibrium** [comment]
> Since the `Profiler` class is static it also has the same lifetime expectation. With this in mind it's not ideal to let some external class clear the `CString` cache

I will have to disagree. The original example provided the user with control of the lifetime of the Profiler. You wouldn't want to have profiler running all the time to potentially tank the FPS in hot path scenarios. 

In fact, on-demand branch was made specifically to allow the user to profile the application at a given moment and ``Dispose`` method was provided so the user can free Profiler data without leaking it.

**Comment by clibequilibrium** [comment]
> ~They should be deallocated automatically since `CString` [implements IDisposable](https://github.com/bottlenoselabs/c2cs/blob/b0441c1417963191a0178ebad82a9bbb9cc991fe/src/cs/production/Bindgen.Runtime/CString.cs#L52-L55)? When the runtime decides to collect a `CString` it should call `Dispose` and free the underlying pointer. It's the same mechanism that drives the call to `TracyEmitZoneEnd` in `ProfilerZone`. This is why you're not seeing memory leaks. Actually, providing C# lifetime to unmanaged objects is the canonical use of `IDisposable`, the fact that people use it to create scope entry/exit semantics is a side effect.~
> 
> Wait I'm reading now that I'm incorrect about this, IDisposable isn't called automatically. The memory should in fact be leaking. I'll uh ... go back to my notes. The part of this post about selecting an appropriate key for the CString cache is still relevant.
> 
> We don't have access to the Tracy [manual lifetime functions](https://github.com/wolfpld/tracy/blob/8b9da2efba6937b66085a52f7281c59293ffe985/public/client/TracyProfiler.hpp#L52-L59) so Tracy expects that the lifetime of the profiling session is equal to the lifetime of the program. Since the `Profiler` class is static it also has the same lifetime expectation. With this in mind it's not ideal to let some external class clear the `CString` cache. You'd likely want to use a (static) finalizer method instead ~though if you read enough of the docs on finalizers you'll see C# really wants you to use `IDisposable` instead, which is what CString does~.
> 
> There _is_ a nontrivial cost to calling `Marshal.StringToHGlobalAnsi`, especially(?) on the file path passed to zones since paths are more likely to be long strings. I wouldn't oppose caching the `CStrings` to avoid this marshaling cost. What cooked my brain when considering this is: **it's not entirely clear to me how Tracy compares zones for equality** and I wouldn't want to simply key the `CString` cache on the zone name (which can be null!) unless it was clear to me that that's how the Profiler app detects equivalent zones. Otherwise we could end up in a situation where we're reusing cached data on zones that Tracy would otherwise consider separate. The Tracy docs aren't clear enough to me to be confident in selecting the proper key for the cache.
> 
> There's also the `TracySourceLocationData` struct that gets generated into the PInvoke class. My brief attempt to use this failed, I'm not actually that experienced with C# interop. If we got this struct working along with `TracyEmitZoneBegin(TracySourceLocationData* srcloc, int active);` then that struct would be ideal for use in the cache instead of having our own struct to hold the data. But again, what's the appropriate key for this?
> 
> ~The sum of all of this is that I don't think we should worry about caching CStrings for now. Sorry for the wall of text I actually did agonize over this for a while before deciding that the given implementation is likely good enough~ my memory about IDisposable functionally was inaccurate.

I am looking at it and it's also strange. In original branch  CString get allocated and is kept in memory (which is expected) because it's referenced in a Dictionary. However, in your PR I don't observe a memory leak on Managed side, nor I see CString allocations so you probably right that Tracy just consumers the pointer and uses it internally. I don't have Visual Studio maybe you could take a look at memory profiler? 

NetMemProfiler_I8qJ9Q8uyv

**Comment by Mervill** [comment]
Help I'm being attacked by a ghost.

Consider the following example program that uses my current changes:

2024-09-22 14_02_31-Tracy - Microsoft Visual Studio

1. Memory is rapidly increasing but some of the reason for this is that Tracy is waiting for a profiler to connect and is caching the profiler data inside the app (this is explicitly **not** using on-demand).
2. I connect to the app with Tracy. The data that Tracy was caching locally gets sent to the profiler so we see the memory go down a bit.
3. However, my changes are indeed leaking CStrings! So even after Tracy is connected we see the memory usage continue to increase.

But uh

2024-09-22 14_05_18-Tracy - Microsoft Visual Studio

Pass a non-zero value to `Thread.Sleep` and all the observed memory effects dissapear. If you examine the graph in detail the memory usage is _slowly_ increasing. But notice that in the first example the memory graph has shifted into the GB range due to the volume of leaked data, but in the second example it's still in the MB range.

Note that in the second example I connected to the app with Tracy just like the first example ... but it's effect isn't noticeable at all?

This appears to work for _any_ non-zero value passed to Sleep, even `sleep(1)`.

Here is the [code](https://gist.github.com/Mervill/bd7b867c2db88625455a00068eecd7b4) as a gist.

I have absolutely no idea what's going on here.

**Comment by Mervill** [comment]
Actually you can eliminate Tracy as a variable entirely by just doing

```C#
while (true)
{
    CString.FromString(randString); // leak memory
    Thread.Sleep(16); // non-zero value makes the memory leak dissapear?
 }
```

or even

```C#
while (true)
{
    Marshal.StringToHGlobalAnsi(randString); // leak memory
    Thread.Sleep(16); // non-zero value makes the memory leak dissapear?
 }
```

**Comment by Mervill** [comment]
~~Ok so part of~~ This discrepancy is just that `Sleep` works on the order of milliseconds so when you do `Sleep(0)` the loop can run at like 1,000,000 loops per second but when `Sleep(1)` is introduced it collapses to like 65 loops per second. So the memory leak 'disappears' into the rounding error of the memory readout. Allocating a much bigger string ~~might make the leak more apparent when using a non-zero value for sleep.~~ like `GetRandomString(65442)` makes the leaking behavior visible even with non-zero Sleep values.

Also I think it's hard to see these problems in memory profiles because this is a leak in _unmanaged_ memory and most of the memory profilers for C# focus on the managed memory. In most of my tests the VS memory profiler says the memory footprint is only a few kilobytes (even when obviously leaking gigabytes) since I designed the code in the gist to allocate no managed memory after it gets into the loop.

**Comment by Mervill** [comment]
Ok I can confidently address the memory leak issue by rewriting `GetCString` so that I can use it with the `using` directive so the strings can get properly disposed. I've just pushed this update. This still side-steps caching any CStrings inside `Profiler`, which I'm not opposed to so long as we can be sure the Key is correct, but the memory leaking issue has been addressed.

**Comment by clibequilibrium** [comment]
> Help I'm being attacked by a ghost.
> 
> Consider the following example program that uses my current changes:
> 
> 2024-09-22 14_02_31-Tracy - Microsoft Visual Studio
> 
> 1. Memory is rapidly increasing but some of the reason for this is that Tracy is waiting for a profiler to connect and is caching the profiler data inside the app (this is explicitly **not** using on-demand).
> 2. I connect to the app with Tracy. The data that Tracy was caching locally gets sent to the profiler so we see the memory go down a bit.
> 3. However, my changes are indeed leaking CStrings! So even after Tracy is connected we see the memory usage continue to increase.
> 
> But uh
> 
> 2024-09-22 14_05_18-Tracy - Microsoft Visual Studio
> 
> Pass a non-zero value to `Thread.Sleep` and all the observed memory effects dissapear. If you examine the graph in detail the memory usage is _slowly_ increasing. But notice that in the first example the memory graph has shifted into the GB range due to the volume of leaked data, but in the second example it's still in the MB range.
> 
> Note that in the second example I connected to the app with Tracy just like the first example ... but it's effect isn't noticeable at all?
> 
> This appears to work for _any_ non-zero value passed to Sleep, even `sleep(1)`.
> 
> Here is the [code](https://gist.github.com/Mervill/bd7b867c2db88625455a00068eecd7b4) as a gist.
> 
> I have absolutely no idea what's going on here.

yea you must be flooding Tracy https://github.com/clibequilibrium/Tracy-CSharp/issues/24

**Comment by clibequilibrium** [comment]
> Ok I can confidently address the memory leak issue by rewriting `GetCString` so that I can use it with the `using` directive so the strings can get properly disposed. I've just pushed this update. This still side-steps caching any CStrings inside `Profiler`, which I'm not opposed to so long as we can be sure the Key is correct, but the memory leaking issue has been addressed.

Awesome! If you can update the PR when you can I will happily merge it. 

Edit: I just saw the latest commit, merging!

**Pull request merged**
